language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_palettepicker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VDLAkaaMe86tpYFea67bNIQzYaTGbO1afTNZR4oPO5rfw2E9v0YY8GLY+hGYhnV8mEDut92xpcIOX9Yxe2DKZAmJOTlwlBF8wplmISsJexuo23EHMyYwpIyOo8MbXNJKvjxZHmyS3rNMQHhvw+aRhwj9nZOeU1UJ2zX2fGvh0KQl7QnlK9mzDhZehv0nUAT1uaPSiuF8RXo3JX7q8siGeIfbwkVa/D2eunOkXpKP1Sz87jkTRypgS1yv2TUpzmEewCHupSz2Dj5jhC4je0tDSshaWFQhBgzgMljk9sWsTMvllYaMm9J7CMsYkbdCnndhSerEqcC8Msq7OC1VjqAPvhqudzdI/G2K6zNfESCVvg1qa+lbbH3/SyT+xNbW8052EV3PcRRy4GoOIHWYDMNcxQLWOc/USnO1DyOqlz+KdgIxfhHwntogwpixaY6iQeVrgQYj+zbPtLr7BMcPIvMQNUMlbH1sF7FdFbpXqwLLZBMS2+0Dsb5LrJh2W/qdUKUrzIDlGrIVFwqY227Mq1tVz8moVQIIGEidYPEeEA1aM2I8ptajKSvCfrzBk3UU+EKoLsjepPpGpWrgRP3cURnvnjRzU+qxhcgDf7PFv0WfC0tjnbeqJoHIIXSgVxmIgs9ARNvfK3WTKIw5S0JZuPatGTxsrALjno9ILmzN/KH57U0=
