language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE test_palettepicker;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ExpmJSQ9bYMG5LRd0/wQMiAFS61tsESbJ1Bzs44xKB6lOxfgorAQ6cjJk5ra6O2GuXHXJXhnfzIZ6/kxiKqFNA6IVcabQGWTeOXg9uCzqntm/kV9rtVefraedAzFTpBlP5g57WNUSv78gwa1s1IDxonWj0N0tAWGEKFxqyRr0PqdeJNRLythMhg2ETM6AZ6qqiAG83Vsp86xh1fKHlRyn1s5C1XF9TULaSdApfZzjP7JOY830exruA2iEecnUSZHW6mY53pzg5VeN+KkTqK3wW4B2RKTD1g2TqkruNajBGCLu7d3YDq1zLWN+kg7RJ5zFP3quk2xCB1srtBAlwH26ML5dmHQdRn3HP+mUtTnREHQgv3RjS8Eg2a1mzujZMuO5inBVywDVd/JVY2CyM+JwjhV32J6hwubeYm72A3qIaspPfRU+qkMFHls2PywC78cJjOwKf7gKi5vR2QfL0omC7UrYWF1ydWGMBA3lNna5YNqc++MHrw1UydRClPb1bzcmr6ISMmK9Rv1AZJdQMQtlzNNoJ4rf9dGxXSjNTaQP6OdagxQqqUdUIRML6wWx6DsaLFDmMDtfT5qMVrkazMZqgQn12HmVf0a6mrNdheUkzIIN19BVFTi9B1rJ/3SPFxbsmZn3EqHC2uJ+8aSI4xUODLVdNuZHFuLE1HX+f4vSqI=
  app: palette-picker-td
  on:
    repo: tdberg21/palette-picker
